# Generated by Django 4.2 on 2025-12-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateEntrySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_payload_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_submissions', to='drivers.driverhelper')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_submissions', to='drivers.driverhelper')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='vehicles.vehicledetails')),
            ],
            options={
                'verbose_name': 'Gate Entry Submission',
                'verbose_name_plural': 'Gate Entry Submissions',
                'db_table': 'GateEntrySubmission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='submissions.gateentrysubmission')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'AuditLog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='gateentrysubmission',
            index=models.Index(fields=['customer_email'], name='GateEntrySu_custome_149c69_idx'),
        ),
        migrations.AddIndex(
            model_name='gateentrysubmission',
            index=models.Index(fields=['qr_payload_hash'], name='GateEntrySu_qr_payl_c18678_idx'),
        ),
        migrations.AddIndex(
            model_name='gateentrysubmission',
            index=models.Index(fields=['status'], name='GateEntrySu_status_8f4e8a_idx'),
        ),
    ]
