# Generated by Django 4.2 on 2025-12-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_gateentrysubmission_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateentrysubmission',
            name='customer',
        ),
    ]
