# Generated by Django 4.2 on 2025-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('truck', 'Truck'), ('car', 'Car'), ('bus', 'Bus'), ('van', 'Van'), ('motorcycle', 'Motorcycle'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='vin_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
