# Generated by Django 4.2 on 2025-12-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicledetails_color_vehicledetails_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetails',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vin_number',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='year',
        ),
    ]
