# Generated by Django 4.2 on 2025-12-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_vehicledetails_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledetails',
            old_name='vehicle_registration_no',
            new_name='vehicleRegistrationNo',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='updated',
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
