ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "is_superuser" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "is_staff" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN DEFAULT TRUE;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "date_joined" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
