# Generated by Django 4.2 on 2025-12-01 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Driver', 'Driver'), ('Helper', 'Helper')], max_length=10)),
                ('phone_no', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +91XXXXXXXXXX', regex='^\\+91\\d{10}$')])),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('ta', 'Tamil')], default='en', max_length=5)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver/Helper',
                'verbose_name_plural': 'Drivers/Helpers',
                'db_table': 'DriverHelper',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='driverhelper',
            index=models.Index(fields=['phone_no'], name='DriverHelpe_phone_n_3027a0_idx'),
        ),
        migrations.AddIndex(
            model_name='driverhelper',
            index=models.Index(fields=['type'], name='DriverHelpe_type_ada4d4_idx'),
        ),
    ]
