# Generated by Django 4.2 on 2025-12-03 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='driverhelper',
            name='DriverHelpe_phone_n_3027a0_idx',
        ),
        migrations.RenameField(
            model_name='driverhelper',
            old_name='is_blacklisted',
            new_name='isBlacklisted',
        ),
        migrations.RemoveField(
            model_name='driverhelper',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='driverhelper',
            name='updated',
        ),
        migrations.AddField(
            model_name='driverhelper',
            name='phoneNo',
            field=models.CharField(default=919999999999, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +91XXXXXXXXXX', regex='^\\+91\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='driverhelper',
            index=models.Index(fields=['phoneNo'], name='DriverHelpe_phoneNo_24cb0e_idx'),
        ),
    ]
