# Generated by Django 4.2 on 2025-12-03 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0002_remove_driverhelper_driverhelpe_phone_n_3027a0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverhelper',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_helpers', to=settings.AUTH_USER_MODEL),
        ),
    ]
