# Generated by Django 4.2 on 2025-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverhelper_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverhelper',
            name='customer',
        ),
        migrations.AlterField(
            model_name='driverhelper',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('bn', 'Bengali'), ('or', 'Odia'), ('pa', 'Punjabi'), ('as', 'Assamese'), ('ur', 'Urdu'), ('sa', 'Sanskrit'), ('mai', 'Maithili')], default='en', max_length=5),
        ),
    ]
