# Generated by Django 4.2 on 2025-12-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('document_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('vehicle_registration', 'Vehicle Registration'), ('vehicle_insurance', 'Vehicle Insurance'), ('puc', 'PUC'), ('driver_license', 'Driver License'), ('transportation_approval', 'Transportation Approval'), ('payment_approval', 'Payment Approval'), ('vendor_approval', 'Vendor Approval')], max_length=50)),
                ('file_path', models.CharField(help_text='Absolute path to document file on storage', max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_extension', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_documents', to='drivers.driverhelper')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='documents.customerdocument')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicledetails')),
            ],
            options={
                'verbose_name': 'Customer Document',
                'verbose_name_plural': 'Customer Documents',
                'db_table': 'CustomerDocument',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerdocument',
            index=models.Index(fields=['customer_email', 'document_type'], name='CustomerDoc_custome_2cda72_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdocument',
            index=models.Index(fields=['is_active'], name='CustomerDoc_is_acti_03d1ba_idx'),
        ),
    ]
