# Generated by Django 4.2 on 2025-12-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_customerdocument_helper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocument',
            name='document_type',
            field=models.CharField(choices=[('vehicle_registration', 'Vehicle Registration'), ('vehicle_insurance', 'Vehicle Insurance'), ('vehicle_puc', 'Vehicle PUC'), ('driver_aadhar', 'Driver Aadhar Card'), ('helper_aadhar', 'Helper Aadhar Card'), ('po', 'Purchase Order (PO)'), ('do', 'Delivery Order (DO)'), ('before_weighing', 'Before Weighing Receipt'), ('after_weighing', 'After Weighing Receipt')], max_length=50),
        ),
    ]
