# Generated by Django 4.2 on 2025-12-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_customerdocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('vehicle_registration', 'Vehicle Registration'), ('vehicle_insurance', 'Vehicle Insurance'), ('vehicle_puc', 'Vehicle PUC'), ('driver_aadhar', 'Driver Aadhar Card'), ('helper_aadhar', 'Helper Aadhar Card'), ('po', 'Purchase Order (PO)'), ('do', 'Delivery Order (DO)'), ('before_weighing', 'Before Weighing Receipt'), ('after_weighing', 'After Weighing Receipt')], max_length=50)),
                ('referenceId', models.IntegerField(blank=True, null=True)),
                ('filePath', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'DocumentControl',
                'ordering': ['-created'],
            },
        ),
    ]
