# Generated by Django 4.2 on 2025-12-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneType',
            fields=[
                ('typeName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('standardTime', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Zone Type',
                'verbose_name_plural': 'Zone Types',
                'db_table': 'ZoneType',
            },
        ),
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='phone',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='empId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='userType',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee')], default='customer', max_length=20),
        ),
        migrations.AlterModelTable(
            name='customeruser',
            table='Users',
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneName', models.CharField(max_length=100)),
                ('isWorking', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('typeName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.zonetype')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'db_table': 'Zone',
            },
        ),
        migrations.AddField(
            model_name='customeruser',
            name='zoneTypeName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.zonetype'),
        ),
    ]
