# Generated by Django 4.2 on 2025-12-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_zonetype_alter_customeruser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
