# Generated by Django 4.2 on 2025-12-03 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_alter_customeruser_last_login_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PODetails',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('expReportingTime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customerUserId', models.ForeignKey(db_column='customerUserId', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('dapName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.zone')),
            ],
            options={
                'verbose_name': 'PO Detail',
                'verbose_name_plural': 'PO Details',
                'db_table': 'PODetails',
                'ordering': ['-created_at'],
            },
        ),
    ]
