# Generated by Django 4.2 on 2025-12-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customeruser_last_login_and_more'),
        ('po_details', '0002_add_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podetails',
            name='dapName',
            field=models.ForeignKey(blank=True, db_column='dapName', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.zone'),
        ),
    ]
