# Generated by Django 4.2 on 2025-12-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0006_fix_customer_fk'),
        ('po_details', '0001_initial'),
        ('drivers', '0004_remove_driverhelper_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVehicleTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('driverId', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.CASCADE, related_name='driver_taggings', to='drivers.driverhelper')),
                ('helperId', models.ForeignKey(blank=True, db_column='helperId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_taggings', to='drivers.driverhelper')),
                ('vehicleId', models.ForeignKey(db_column='vehicleId', on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicledetails')),
            ],
            options={
                'verbose_name': 'Driver Vehicle Tagging',
                'verbose_name_plural': 'Driver Vehicle Taggings',
                'db_table': 'DriverVehicleTagging',
            },
        ),
        migrations.CreateModel(
            name='RFTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeployed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'RF Tag',
                'verbose_name_plural': 'RF Tags',
                'db_table': 'RFTags',
            },
        ),
        migrations.CreateModel(
            name='PODriverVehicleTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actReportingTime', models.DateTimeField(blank=True, null=True)),
                ('exitTime', models.DateTimeField(blank=True, null=True)),
                ('driverVehicleTaggingId', models.ForeignKey(db_column='driverVehicleTaggingId', on_delete=django.db.models.deletion.CASCADE, to='podrivervehicletagging.drivervehicletagging')),
                ('poId', models.ForeignKey(db_column='poId', on_delete=django.db.models.deletion.CASCADE, to='po_details.podetails')),
                ('rftagId', models.ForeignKey(blank=True, db_column='rftagId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='podrivervehicletagging.rftags')),
            ],
            options={
                'verbose_name': 'PO Driver Vehicle Tagging',
                'verbose_name_plural': 'PO Driver Vehicle Taggings',
                'db_table': 'PODriverVehicleTagging',
            },
        ),
    ]
